version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: your_database_name
    volumes:
      - ./tms:/var/www/html
  web:
    build: .
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
volumes:
  db_data:
